const std = @import("std");
const builtin = @import("builtin");

fn androidTriple(target: std.Target) []const u8 {
    return switch (target.cpu.arch) {
        .aarch64 => "aarch64-linux-android",
        .x86_64 => "x86_64-linux-android",
        else => @panic("NovaScale only builds arm64-v8a and x86_64"),
    };
}

fn ndkPrebuiltTag() []const u8 {
    const os_part = switch (builtin.os.tag) {
        .linux => "linux",
        .macos => "darwin",
        .windows => "windows",
        else => @panic("unsupported build host"),
    };
    const arch_part = switch (builtin.cpu.arch) {
        .x86_64 => "x86_64",
        .aarch64 => if (builtin.os.tag == .macos) "x86_64" else "aarch64",
        else => @panic("unsupported build host architecture"),
    };
    return std.fmt.comptimePrint("{s}-{s}", .{ os_part, arch_part });
}

fn createLibC(
    b: *std.Build,
    target: std.Target,
    api: u32,
    sysroot: []const u8,
) std.Build.LazyPath {
    const triple = androidTriple(target);
    const contents = b.fmt(
        \\# Generated by the NovaScale Ghostty build. DO NOT EDIT.
        \\
        \\include_dir={s}/usr/include
        \\
        \\sys_include_dir={s}/usr/include/{s}
        \\
        \\crt_dir={s}/usr/lib/{s}/{d}
        \\
        \\msvc_lib_dir=
        \\
        \\kernel32_lib_dir=
        \\
        \\gcc_dir=
    , .{ sysroot, sysroot, triple, sysroot, triple, api });
    const generated = b.addWriteFiles();
    return generated.add(b.fmt("android-libc-{s}-{d}.conf", .{ triple, api }), contents);
}

pub fn build(b: *std.Build) void {
    const optimize = b.standardOptimizeOption(.{});
    const abi = b.option([]const u8, "abi", "Android ABI: arm64-v8a or x86_64") orelse "arm64-v8a";
    const api = b.option(u32, "android-api", "Android API level") orelse 28;
    const query: std.Target.Query = if (std.mem.eql(u8, abi, "arm64-v8a"))
        .{ .cpu_arch = .aarch64, .os_tag = .linux, .abi = .android, .android_api_level = api }
    else if (std.mem.eql(u8, abi, "x86_64"))
        .{ .cpu_arch = .x86_64, .os_tag = .linux, .abi = .android, .android_api_level = api }
    else
        @panic("-Dabi must be arm64-v8a or x86_64");
    const target = b.resolveTargetQuery(query);

    const ghostty = b.dependency("ghostty", .{
        .target = target,
        .optimize = optimize,
        .simd = false,
    });
    const module = b.createModule(.{
        .root_source_file = b.path("src/nova_ghostty.zig"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
        .strip = true,
        .unwind_tables = .none,
        .omit_frame_pointer = true,
    });
    module.addImport("ghostty-vt", ghostty.module("ghostty-vt"));

    const library = b.addLibrary(.{
        .linkage = .static,
        .name = "nova_ghostty",
        .root_module = module,
    });
    library.link_function_sections = true;
    library.link_data_sections = true;
    library.link_gc_sections = true;

    const ndk = b.graph.env_map.get("ANDROID_NDK_HOME") orelse
        b.graph.env_map.get("ANDROID_NDK_ROOT") orelse
        @panic("ANDROID_NDK_HOME is required");
    const sysroot = b.pathJoin(&.{ ndk, "toolchains", "llvm", "prebuilt", ndkPrebuiltTag(), "sysroot" });
    const libc_file = createLibC(b, target.result, api, sysroot);
    library.setLibCFile(libc_file);
    library.linkLibC();
    b.installArtifact(library);

    const fmt = b.addFmt(.{ .paths = &.{ "build.zig", "build.zig.zon", "src" } });
    b.step("fmt", "Check Zig formatting").dependOn(&fmt.step);
}
